name: pretty_qr_code_example
description: Pretty QR code example app.

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  web: any
  path_provider: 2.0.15

  pretty_qr_code:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
