name: example
description: A new Flutter project.

version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  pretty_qr_code:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - images/
