name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.0.0'

      - name: Setup lcov
        run:  sudo apt-get -y install lcov

      - name: Install Dependencies
        run: flutter pub get

      - name: Test
        run: |
          flutter test --no-pub --test-randomize-ordering-seed random --coverage
          lcov -r coverage/lcov.info -o coverage/lcov.info
